use std::collections::HashMap;

/// Github-slugger compatible slug generator.
#[derive(Default)]
pub struct Slugger {
    counts: HashMap<String, usize>,
}

impl Slugger {
    /// Creates a new slugger.
    pub fn new() -> Self {
        Self {
            counts: HashMap::new(),
        }
    }

    /// Generates the next slug for the given heading text.
    pub fn next_slug(&mut self, text: &str) -> String {
        slugify(text, &mut self.counts)
    }
}

/// Slugify the given text, updating counts to ensure uniqueness.
///
/// Matches github-slugger's algorithm:
/// 1. Lowercase
/// 2. Remove all non-alphanumeric, non-space characters
/// 3. Replace only spaces with hyphens
/// 4. No trailing-hyphen trimming, no consecutive-hyphen collapsing
pub fn slugify(text: &str, counts: &mut HashMap<String, usize>) -> String {
    let mut slug = String::new();

    for ch in text.chars() {
        if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
            slug.push(ch.to_ascii_lowercase());
        } else if !ch.is_ascii() && ch.is_alphanumeric() {
            // Keep unicode letters/digits; lowercase where possible
            for lower in ch.to_lowercase() {
                slug.push(lower);
            }
        } else if ch == ' ' {
            slug.push('-');
        }
        // All other characters (punctuation, tabs, newlines, etc.) are silently dropped
    }

    // empty fallback
    if slug.is_empty() {
        slug.push_str("heading");
    }

    let entry = counts.entry(slug.clone()).or_insert(0);
    if *entry > 0 {
        slug.push_str(&format!("-{}", *entry));
    }
    *entry += 1;

    slug
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ascii_basic() {
        let mut counts = HashMap::new();
        assert_eq!(slugify("Hello World", &mut counts), "hello-world");
    }

    #[test]
    fn deduplication() {
        let mut counts = HashMap::new();
        assert_eq!(slugify("Title", &mut counts), "title");
        assert_eq!(slugify("Title", &mut counts), "title-1");
        assert_eq!(slugify("Title", &mut counts), "title-2");
    }

    #[test]
    fn unicode_preserved() {
        let mut counts = HashMap::new();
        assert_eq!(slugify("多言語 ガイド", &mut counts), "多言語-ガイド");
    }

    #[test]
    fn spaces_become_hyphens_no_collapsing_or_trimming() {
        let mut counts = HashMap::new();
        // Spaces → hyphens, hyphens preserved, no collapsing, no trimming
        assert_eq!(slugify("  a---b  ", &mut counts), "--a---b--");
    }

    #[test]
    fn dots_removed() {
        let mut counts = HashMap::new();
        assert_eq!(slugify("import.meta.glob", &mut counts), "importmetaglob");
    }

    #[test]
    fn trailing_hyphen_preserved() {
        let mut counts = HashMap::new();
        // `<Image />` → angle brackets and slash removed, space becomes hyphen
        assert_eq!(slugify("<Image />", &mut counts), "image-");
    }

    #[test]
    fn dots_in_config_keys() {
        let mut counts = HashMap::new();
        assert_eq!(slugify("build.format", &mut counts), "buildformat");
        assert_eq!(slugify("i18n.locales", &mut counts), "i18nlocales");
    }

    /// Verify parity with github-slugger for real Astro docs headings.
    /// Expected values generated by: `require('github-slugger').slug(input)`
    #[test]
    fn github_slugger_parity() {
        let cases: Vec<(&str, &str)> = vec![
            ("Hello World", "hello-world"),
            ("import.meta.glob", "importmetaglob"),
            ("<Image />", "image-"),
            ("build.format", "buildformat"),
            ("i18n.locales", "i18nlocales"),
            ("多言語 ガイド", "多言語-ガイド"),
            ("  a---b  ", "--a---b--"),
            ("src/content/", "srccontent"),
            ("astro.config.mjs", "astroconfigmjs"),
            ("Astro.props", "astroprops"),
            ("define:vars", "definevars"),
            ("client:load", "clientload"),
            ("set:html", "sethtml"),
            ("is:inline", "isinline"),
            ("class:list", "classlist"),
            ("transition:name", "transitionname"),
            ("getStaticPaths()", "getstaticpaths"),
            ("Content Collections", "content-collections"),
            ("Why Astro?", "why-astro"),
            ("<Fragment />", "fragment-"),
            ("TypeScript & JSX", "typescript--jsx"),
            ("node_modules/.astro", "node_modulesastro"),
            ("public/", "public"),
            ("@astrojs/mdx", "astrojsmdx"),
            ("import.meta.env", "importmetaenv"),
            ("Markdown & MDX", "markdown--mdx"),
            ("<Code />", "code-"),
            ("astro:content", "astrocontent"),
            ("Using __dirname", "using-__dirname"),
        ];

        for (input, expected) in &cases {
            let mut counts = HashMap::new();
            let actual = slugify(input, &mut counts);
            assert_eq!(
                &actual, expected,
                "Mismatch for {:?}: got {:?}, expected {:?}",
                input, actual, expected
            );
        }
    }
}
